"""empty message

Revision ID: 0cbb714327c9
Revises: 286de5c6bcc1
Create Date: 2023-08-14 21:47:17.562539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0cbb714327c9'
down_revision = '286de5c6bcc1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wikis',
    sa.Column('page_name', sa.String(length=80), nullable=False),
    sa.Column('page_title', sa.String(length=80), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('page_name'),
    sa.UniqueConstraint('page_title')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wikis')
    # ### end Alembic commands ###
