"""add ipam

Revision ID: a59e6e1c1032
Revises: 0cbb714327c9
Create Date: 2023-08-20 01:12:55.353547

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a59e6e1c1032'
down_revision = '0cbb714327c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ip_addresses',
    sa.Column('ipv4_address', sa.String(length=15), nullable=False),
    sa.Column('ipv4_cidr', sa.String(length=2), nullable=False),
    sa.Column('device', sa.String(length=80), nullable=False),
    sa.Column('location', sa.String(length=80), nullable=False),
    sa.Column('DHCP', sa.Boolean(), nullable=True),
    sa.Column('MAC', sa.String(length=17), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('MAC'),
    sa.UniqueConstraint('device'),
    sa.UniqueConstraint('ipv4_address'),
    sa.UniqueConstraint('ipv4_cidr')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ip_addresses')
    # ### end Alembic commands ###
